export const userRoutes = {

    GET_PROFILE_BY_NAME_REQUEST: 'GET_PROFILE_BY_NAME_REQUEST',
    GET_PROFILE_BY_NAME_RESPONSE: 'GET_PROFILE_BY_NAME_RESPONSE',

    GET_PROFILE_BY_ID_REQUEST: 'GET_PROFILE_BY_ID_REQUEST',
    GET_PROFILE_BY_ID_RESPONSE: 'GET_PROFILE_BY_ID_RESPONSE',

    SEARCH_USERS_REQUEST: 'SEARCH_USERS_REQUEST',
    SEARCH_USERS_RESPONSE: 'SEARCH_USERS_RESPONSE',

    GET_ACTIVE_FRIENDS_REQUEST: 'GET_ACTIVE_FRIENDS_REQUEST',
    GET_ACTIVE_FRIENDS_RESPONSE: 'GET_ACTIVE_FRIENDS_RESPONSE',

    GET_WORK_AND_EXPERIENCE_REQUEST: 'GET_WORK_AND_EXPERIENCE_REQUEST',
    GET_WORK_AND_EXPERIENCE_RESPONSE: 'GET_WORK_AND_EXPERIENCE_RESPONSE',

    SET_WORK_AND_EXPERIENCE_REQUEST: 'SET_WORK_AND_EXPERIENCE_REQUEST',
    SET_WORK_AND_EXPERIENCE_RESPONSE: 'SET_WORK_AND_EXPERIENCE_RESPONSE',

    GET_USER_SETTINGS_REQUEST: 'GET_USER_SETTINGS_REQUEST',
    GET_USER_SETTINGS_RESPONSE: 'GET_USER_SETTINGS_RESPONSE',

    SET_USER_SETTINGS_REQUEST: 'SET_USER_SETTINGS_REQUEST',
    SET_USER_SETTINGS_RESPONSE: 'SET_USER_SETTINGS_RESPONSE',

    GET_PLACES_REQUEST: 'GET_PLACES_REQUEST',
    GET_PLACES_RESPONSE: 'GET_PLACES_RESPONSE',

    SET_PLACES_REQUEST: 'SET_PLACES_REQUEST',
    SET_PLACES_RESPONSE: 'SET_PLACES_RESPONSE',

    CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
    CREATE_POST_RESPONSE: 'CREATE_POST_RESPONSE',

    EDIT_POST_REQUEST: 'EDIT_POST_REQUEST',
    EDIT_POST_RESPONSE: 'EDIT_POST_RESPONSE',

    DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
    DELETE_POST_RESPONSE: 'DELETE_POST_RESPONSE',

    SAVE_POST_REQUEST: 'SAVE_POST_REQUEST',
    SAVE_POST_RESPONSE: 'SAVE_POST_RESPONSE',

    UNSAVE_POST_REQUEST: 'UNSAVE_POST_REQUEST',
    UNSAVE_POST_RESPONSE: 'UNSAVE_POST_RESPONSE',

    SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
    SEND_MESSAGE_RESPONSE: 'SEND_MESSAGE_RESPONSE',

    GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
    GET_MESSAGES_RESPONSE: 'GET_MESSAGES_RESPONSE',

    SET_MESSAGE_STATUS_REQUEST: 'SET_MESSAGE_STATUS_REQUEST',
    SET_MESSAGE_STATUS_RESPONSE: 'SET_MESSAGE_STATUS_RESPONSE',

    GET_FRIEND_REQUESTS_REQUEST: 'GET_FRIEND_REQUESTS_REQUEST',
    GET_FRIEND_REQUESTS_RESPONSE: 'GET_FRIEND_REQUESTS_RESPONSE',

    SEND_REQUEST_REQUEST: 'SEND_REQUEST_REQUEST',
    SEND_REQUEST_RESPONSE: 'SEND_REQUEST_RESPONSE',

    ACCEPT_REQUEST_REQUEST: 'ACCEPT_REQUEST_REQUEST',
    ACCEPT_REQUEST_RESPONSE: 'ACCEPT_REQUEST_RESPONSE',

    REJECT_REQUEST_REQUEST: 'REJECT_REQUEST_REQUEST',
    REJECT_REQUEST_RESPONSE: 'REJECT_REQUEST_RESPONSE',

    UNFRIEND_REQUEST: 'UNFRIEND_REQUEST',
    UNFRIEND_RESPONSE: 'UNFRIEND_RESPONSE',

    FOLLOW_REQUEST: 'FOLLOW_REQUEST',
    FOLLOW_RESPONSE: 'FOLLOW_RESPONSE',

    UNFOLLOW_REQUEST: 'UNFOLLOW_REQUEST',
    UNFOLLOW_RESPONSE: 'UNFOLLOW_RESPONSE',
};

export const authRoutes = {
    CHECK_USERNAME_REQUEST: 'CHECK_USERNAME_REQUEST',
    CHECK_USERNAME_RESPONSE: 'CHECK_USERNAME_RESPONSE',

    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_RESPONSE: 'LOGIN_USER_RESPONSE',

    LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST',
    LOGOUT_USER_RESPONSE: 'LOGOUT_USER_RESPONSE',

    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_RESPONSE: 'CREATE_USER_RESPONSE',
};